version: '3'
services:
  db:
    image: postgres
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER={DB_USER}
      - POSTGRES_DB={DB_DATABASE_NAME}
